apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    region: {{ .Values.provider.region }}
    name: '{{ .Values.cluster }}'
    cluster.open-cluster-management.io/clusterset: all-openshift-clusters
  name: '{{ .Values.cluster }}'
  namespace: '{{ .Values.cluster }}' 
spec:
  hubAcceptsClient: true
