apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-pull-secret
  namespace: {{ .Values.cluster }}
spec: 
  encryptedData:
    .dockerconfigjson: {{ .Values.provider.pullSecret }}
  template: 
    data: null
    metadata:
      name: {{ .Values.cluster }}-pull-secret
      namespace: '{{ .Values.cluster }}'
    type: kubernetes.io/dockerconfigjson
