apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- aws-tokyo-apps-appsub.yaml
- aws-tokyo-apps-app.yaml
- aws-tokyo-apps-channel.yaml
- aws-tokyo-apps-placementrule.yaml