apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: '{{ .Values.cluster }}'
  namespace: '{{ .Values.cluster }}'
  labels:
    cloud: 'vSphere'
    vendor: 'OpenShift'
    hive.openshift.io/cluster-platform: vsphere

spec:
  baseDomain: {{ .Values.provider.baseDomain }}
  clusterName: '{{ .Values.cluster }}'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 2
  platform:
    vsphere:
      cluster: {{ .Values.provider.vmClusterName }} 
      certificatesSecretRef:
        name: {{ .Values.cluster }}-vsphere-certs
      credentialsSecretRef:
        name: {{ .Values.cluster }}-vsphere-creds
      vCenter: {{ .Values.provider.vcenter }} 
      datacenter: {{ .Values.provider.datacenter }} 
      defaultDatastore: {{ .Values.provider.datastore }} 
      network: {{ .Values.network.networkName }} 
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.cluster }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.cluster }}-ssh-private-key
    imageSetRef:
      name: {{ .Values.imageName }}
  pullSecretRef:
    name: {{ .Values.cluster }}-pull-secret
