apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-azure-creds
  namespace: {{.Values.cluster }}
spec:
  encryptedData:
    osServicePrincipal.json: |-
      {{ .Values.provider.azure_creds }}
  template:
    data: null
    metadata:
      name: {{ .Values.cluster }}-azure-creds
      namespace: '{{ .Values.cluster }}'