apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ibm-cp4i-argocd
  namespace: openshift-gitops
  labels:
    app: ibm-cp4i-argocd
  annotations:
      apps.open-cluster-management.io/github-path: 0-bootstrap/single-cluster/bootstrap.yaml
spec:
  channel: ibm-cp4i-argocd/ibm-cp4i-argocd
  placement:
    placementRef:
      kind: PlacementRule
      name: ibm-cp4i-argocd
#      apiGroup: apps.open-cluster-management.io