apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: '{{ .Values.cluster }}'
  namespace: '{{ .Values.cluster }}'
spec:
  clusterName: '{{ .Values.cluster }}'
  clusterNamespace: '{{ .Values.cluster }}'
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.2.0
