apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-install-config
  namespace: {{ .Values.cluster }}
spec:
  encryptedData:
    # Base64 encoding of install-config yaml
    install-config.yaml: {{ .Values.provider.installConfig }} 
  template:
    metadata:
      name: {{ .Values.cluster }}-install-config
      namespace: '{{ .Values.cluster }}'
    type: Opaque
