apiVersion: v1
metadata:
  name: '{{ .Values.cluster }}' 
baseDomain: {{ .Values.provider.baseDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ .Values.masters.count }}
  platform:
    aws:
      rootVolume:
        iops: {{ .Values.masters.diskIops }}
        size: {{ .Values.masters.diskSize }} 
        type: {{ .Values.masters.diskType }}
      type: {{ .Values.masters.machineType }}
compute:
- hyperthreading: Enabled
  name: 'worker'
  replicas: {{ .Values.workers.count }}
  platform:
    aws:
      rootVolume:
        iops: {{ .Values.workers.diskIops }}
        size: {{ .Values.workers.diskSize }} 
        type: {{ .Values.workers.diskType }}
      type: {{ .Values.workers.machineType }}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {{ .Values.provider.region }}
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    {{ .Values.provider.sshPublickey }}
