apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-policies 
  namespace: openshift-gitops
  labels:
    app: cluster-policies 
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - cluster-policies